-- Credit card statement cycles + recurring-rule period tracking.
--
-- 1. Splits a card's single date into two: statement_day closes a cycle,
--    due_day is when that closed cycle must be paid. 0005's `billing_day`
--    already held due days, so it is renamed rather than reused.
-- 2. `last_settled_statement` records which statement autopay last paid,
--    keyed by that statement's close date, so a cycle spanning two calendar
--    months is not mistaken for one already settled.
-- 3. `recurring_rules.last_posted_period` records which cycle was last posted,
--    so the UI can say "paid for August" and a double click can be rejected.

alter table moneyos.accounts rename column billing_day to due_day;

-- The 1-28 check follows the renamed column automatically; only its name is
-- stale. Guarded because an autogenerated constraint name is not worth failing
-- a migration over.
do $$
begin
  if exists (select 1 from pg_constraint where conname = 'accounts_billing_day_check'
             and conrelid = 'moneyos.accounts'::regclass) then
    alter table moneyos.accounts rename constraint accounts_billing_day_check to accounts_due_day_check;
  end if;
end $$;

alter table moneyos.accounts
  add column statement_day int check (statement_day between 1 and 28),
  add column last_settled_statement date;

alter table moneyos.recurring_rules
  add column last_posted_period date;

-- Rules that have already posted at least once: the cycle they posted was
-- exactly one interval before whatever next_run_date now points at.
update moneyos.recurring_rules
set last_posted_period = (next_run_date - (interval_count * case frequency
    when 'daily' then interval '1 day'
    when 'weekly' then interval '1 week'
    when 'yearly' then interval '1 year'
    else interval '1 month'
  end))::date
where last_run_date is not null;
