-- Credit card statement cycles + recurring-rule period tracking.
--
-- 1. A real credit card has two dates, not one: the *statement (billing) day*
--    that closes a cycle, and the *due day* by which that closed cycle has to
--    be paid. 0005 only had `billing_day`, and the UI labelled it "Bill due
--    day" - so every value already stored under it is a due day. Rename it to
--    say what it actually holds, and add the statement day alongside.
--    Spend that lands after the statement day belongs to the *next* cycle,
--    even though the current cycle's due date hasn't passed yet.
-- 2. `last_settled_statement` records which statement autopay last paid
--    (keyed by that statement's close date), replacing the previous
--    "same calendar month as autopay_last_run" guess - a cycle that closes
--    on the 18th and is due on the 5th of the next month spans two months,
--    which the month-string check got wrong. `autopay_last_run` stays as the
--    plain "when did the catch-up pass last act on this card" timestamp.
-- 3. `recurring_rules.last_posted_period` records *which cycle* was last
--    posted (the next_run_date that was consumed), so the UI can say "paid
--    for August" instead of just "posted on the 2nd", and so a double-click
--    on "Mark paid" can be rejected server-side instead of silently posting
--    the next cycle too.

alter table moneyos.accounts rename column billing_day to due_day;

-- Cosmetic: the 1-28 check follows the renamed column automatically, only its
-- name still says billing_day. Guarded because the constraint's autogenerated
-- name isn't worth failing a migration over.
do $$
begin
  if exists (select 1 from pg_constraint where conname = 'accounts_billing_day_check'
             and conrelid = 'moneyos.accounts'::regclass) then
    alter table moneyos.accounts rename constraint accounts_billing_day_check to accounts_due_day_check;
  end if;
end $$;

alter table moneyos.accounts
  add column statement_day int check (statement_day between 1 and 28),
  add column last_settled_statement date;

alter table moneyos.recurring_rules
  add column last_posted_period date;

-- Rules that have already posted at least once: the cycle they posted was
-- exactly one interval before whatever next_run_date now points at.
update moneyos.recurring_rules
set last_posted_period = (next_run_date - (interval_count * case frequency
    when 'daily' then interval '1 day'
    when 'weekly' then interval '1 week'
    when 'yearly' then interval '1 year'
    else interval '1 month'
  end))::date
where last_run_date is not null;
